export enum Click2PayErrors {
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  SERVICE_ERROR = 'SERVICE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  INVALID_REQUEST = 'INVALID_REQUEST',
  AUTH_ERROR = 'AUTH_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  ACCT_INACCESSIBLE = 'ACCT_INACCESSIBLE',
  CODE_INVALID = 'CODE_INVALID',
  RETRIES_EXCEEDED = 'RETRIES_EXCEEDED',
  CARD_INVALID = 'CARD_INVALID',
}
