export enum Click2PayCheckoutActionCode {
  COMPLETE = 'COMPLETE',
  CANCEL = 'CANCEL',
  ERROR = 'ERROR',
  CHANGE_CARD = 'CHANGE_CARD',
  ADD_CARD = 'ADD_CARD',
  SWITCH_CONSUMER = 'SWITCH_CONSUMER',
}
