export const images = {
  logoMoreFull: '/images/logo-more-full.svg',
  logoMoreSmall: '/images/logo-more-small.svg',
  homeCarousel01: '/images/home_carousel_01.png',
  homeCarousel02: '/images/home_carousel_02.png',
  homeCarousel03: '/images/home_carousel_03.png',
  homeCarousel04: '/images/home_carousel_04.png',
  cardMorePrepaid: '/images/card-more-prepaid.svg',
  cardMorePayrollDeduct: '/images/card-more-payroll-deduct.svg ',
  cardBakktNotConnected: '/images/card-bakkt-not-connected.svg',
  cardBakktConnected: '/images/card-bakkt-connected.svg',
  signOut: '/images/sign-out.png',
  appleWallet: '/images/apple-wallet.svg',
  googlePay: '/images/google-pay.svg',
  googlePayDisabled: '/images/google-pay-disabled.svg',
  walletCard: '/images/wallet-card.svg',
};
